Add simplified chinese localization
EdgeTX/buddy pull request #23
Opened 2022-04-02 10:01 UTC by L1cardo

2022-04-02 10:10 UTC, freshollie commented
谢谢你! 

Looks like you’ve included some extra “,” at the end of some files. JSON doesn’t like this hence failing to compile. It will also be worth running “yarn extract-locales” locally as this will put the translations in the correct order in the files.

2022-04-02 10:11 UTC, L1cardo commented
Oh！ Sorry for the extra “,” , I just realize that these are all JSON files, I will fix them right now

2022-04-02 17:30 UTC, freshollie commented on locales/zh/flashing.json
> +  "Done": "完成",
To clarify, this is a button to confirm "I'm done"

It's the "Done" button in the bottom right after flashing has completed. Not done like finished I guess?

2022-04-02 17:36 UTC, freshollie commented
Looks good apart from the `Done` translation. What is `[.output/buddy.box](https://github.com/EdgeTX/buddy/pull/23/files#diff-94ae4b18fb5cc1aba4e47ff988b6051430f3bac6cb10d4d5747387f702935c37)`?

2022-04-02 17:38 UTC, freshollie commented on locales/zh/flashing.json
> +  "Done": "完成",
This translation may be right, just wanted to clarify that it's to do with a button and not to notify that something is done.

2022-04-03 00:28 UTC, L1cardo commented on locales/zh/flashing.json
> +  "Done": "完成",
”完成” can mean "done" or "finished", that's makes you confused. It's correct though.

2022-04-03 11:07 UTC, freshollie requested changes
@L1cardo I will merge once `.output/buddy.box` is removed

2022-04-03 11:12 UTC, L1cardo commented
> @L1cardo I will merge once `.output/buddy.box` is removed

Removed! Sorry for my carelessness. 😅

2022-04-03 11:27 UTC, freshollie approved these changes

2022-04-03 11:28 UTC, merged